folder_input: "input"
folder_output: "output"
# categories can be one of these:
# PERSON, GEO, ORG, PRODUCT, EVENT, KEYWORD, FUNCTION, NUMBER, DATE, CURRENCY, URL, QUOTE
categories:
  - PERSON
  - GEO
  - ORG
engines:
  simple:
    labels:
      "GPE": "GEO"
      "LOCATION": "GEO"
      "ORGANIZATION": "ORG"
      "PERSON": "PERSON"
      "FACILITY": "KEYWORD"
      "GSP": "ORG"
  alchemy:
    key: 7d834fdf730ac8adc0443863068fd16d291b818b
    # see http://www.alchemyapi.com/api/entity/types
    labels:
      "City": "GEO"
      "Facility": "GEO"
      "StateOrCounty": "GEO"
      "Country": "GEO"
      "Region": "GEO"
      "Continent": "GEO"
      "GeographicFeature": "GEO"
      "Person": "PERSON"
      "Company": "ORG"
      "Organization": "ORG"
      "PrintMedia": "ORG"
      "JobTitle": "FUNCTION"
      "Quantity": "NUMBER"
      "SportingEvent": "EVENT"
      "Drug": "KEYWORD"
      "HealthCondition": "KEYWORD"
      "FieldTerminology": "KEYWORD"
      "Sport": "KEYWORD"
      "Technology": "KEYWORD"
      "EntertainmentAward": "KEYWORD"
      "Holiday": "EVENT"
      "TelevisionStation": "ORG"
      "Crime": "KEYWORD"
  basistech:
    host: "http://192.168.59.103:9020"
    labels:
      "PERSON": "PERSON"
      "LOCATION": "GEO"
      "TITLE": "FUNCTION"
      "TEMPORAL:DATE": "DATE"
      "ORGANIZATION": "ORG"
      "IDENTIFIER:URL": "URL"
      "TEMPORAL:TIME": "DATE"
      "IDENTIFIER:DISTANCE": "NUMBER"
      "IDENTIFIER:MONEY": "CURRENCY"
      "RELIGION": "KEYWORD"
      "NATIONALITY": "KEYWORD"
      "PRODUCT": "PRODUCT"
  bitext:
    user: amaier1
    passwd: Qp76dY1DQ
    labels:
      19: "NUMBER"
      15: "CURRENCY"
      11: "DATE"
      10: "DATE"
      8: "URL"
      7: "ORG"
      6: "ORG"
      3: "GEO"
      1: "PERSON"
      0: "KEYWORD"
    langs:
      "en": "ENG"
      "de": "DEU"
      "es": "ESP"
      "pt": "POR"
      "it": "ITA"
      "fr": "FRA"
      "nl": "NLD"
      "ca": "CAT"
  linguasys:
    key: a0fa546f85ca4bbfb55bab69aa2c5a4f
    labels:
      "person" : "PERSON"
      "location": "GEO"
      "organisation": "ORG"
      "administrative unit": "ORG"
      "date" : "DATE"
      "time" : "DATE"
      "aspect" : "KEYWORD"
      "abbreviation" : "KEYWORD"
    # conversion from ISO_639-1 to linguasys language codes (see https://nlp.linguasys.com/Languages)
    langs:
      "en": "ENG"
  meaningcloud:
    key: dbc8c605163c8e789c2faaa9ce05fbde
    labels:
      "Top>Location": "GEO"
      "Top>Person": "PERSON"
      "Top>Organization": "ORG"
      "Top>Product": "PRODUCT"
      "Top>Event": "EVENT"
      "Top>OtherEntity": "KEYWORD"
      "Top>Timex": "DATE"
      "Top": "KEYWORD"
  netowl:
    key: a09820f5-4f82-4c26-a5a9-1724e985a776
    labels:
      "entity:person": "PERSON"
      "entity:place": "GEO"
      "entity:organization": "ORG"
      "entity:time": "DATE"
      "entity:other": "KEYWORD"
      "entity:numeric": "NUMBER"
      "entity:address": "URL"
      "entity:artifact": "PRODUCT"
    langs:
      "en": "nametag-english-sentiment-analysis-ignoresgml-json"
      "fr": "nametag-french-ignoresgml-json"
  repustate:
    key: 317542394cddce0baf6b3ec698d92198e2b6e4a7
    # see also here: https://www.repustate.com/media/entities.txt
    labels:
      "government.politician": "PERSON"
      "location.citytown": "GEO"
      "location.us_state": "GEO"
      "location.country": "GEO"
      "location.region": "GEO"
      "location.continent": "GEO"
      "location.nationality": "KEYWORD"
      "business.businessmen": "PERSON"
      "government.agency": "ORG"
      "government.political_party": "ORG"
      "government.us_presidents": "PERSON"
      "government.position": "FUNCTION"
      "business.job_title": "FUNCTION"
      "business.brand": "PRODUCT"
      "business.oil_and_gas_drilling_and_exploration": "ORG"
      "business.apparel_stores": "PRODUCT"
      "time.month": "DATE"
      "time.day": "DATE"
      "time.season": "DATE"
      "news.network": "ORG"
      "health.disease": "KEYWORD"
      "health.vaccine": "KEYWORD"
      "travel.hotel": "KEYWORD"
      "travel.accommodation": "KEYWORD"
      "health.physician": "PERSON"
      "sports.sports_team_coach": "PERSON"
      "sports.pro_athlete": "PERSON"
      "finance.currency": "CURRENCY"
      "automotive.model": "PRODUCT"
      "automotive.company": "ORG"
      "music.album": "PRODUCT"
  retresco:
    key: 1A5319EA-4AA0-48D8-8010-7952863851D0
    host: "https://rtr.ipool.asideas.de"
    server_cert: "rtr_ipool.pem"
    labels:
      "geos": "GEO"
      "persons": "PERSON"
      "orgs": "ORG"
      "products": "PRODUCT"
      "keywords": "KEYWORD"
      "events": "EVENT"
  semantria:
    key: 1e9489fd-9870-45c3-9cd2-0890aafad3fa
    secret: 02f32cbb-0e0a-4150-a93a-b36d28b99cfd
    # see http://support.semantria.com/customer/portal/articles/838464-entity-extraction
    labels:
      "Place": "GEO"
      "Person": "PERSON"
      "Product": "PRODUCT"
      "Company": "ORG"
      "Job Title": "FUNCTION"
      "Quote": "QUOTE"
      "Pattern": "KEYWORD"
      "vehicle": "PRODUCT"
    # in semantria the configuration is stored on the server and has an id
    # You can get the config id for a language via
    # for key in session.getConfigurations(): print key["language"],key["config_id"]
    langs:
      "ko": "bc399d26-9b33-4f00-a7fe-cb343f8a3756"
      "it": "72bad261-4240-4cf6-b3e3-5fb27bc9c619"
      "jp": "ebda1e20-d666-4533-9614-1e3d02bcb22c"
      "fr": "aa2141a3-f990-4296-a82b-daf7f2ee9d9e"
      "pt": "5aa3cc21-7c82-463a-8307-de815573e4ed"
      "en": "10781931-a7cc-4ff8-aae1-5bda0a7fcec9"
      "ms": "d9f02606-f087-45e4-9643-77d0ddd4f4cc"
      "de": "04854264-0288-420f-8954-104ab6cc5b1a"
      "es": "bd5e9a9b-3772-460c-9fd3-3915ee9c95ec"
      "zh": "2fc65284-5743-4ff4-b239-331ac9b03a7a"
  temis:
    host: "http://193.28.233.173:8091"
    labels:
      "/Entity/Person": "PERSON"
      "/Entity/Location": "GEO"
      "/Entity/Company" : "ORG"
      "/Entity/Organisation": "ORG"
      "/Entity/Media" : "ORG"
      "/Entity/Function": "FUNCTION"
  textrazor:
    key: 18f6730269b89e61a2d9c89853960328aa5511226830cf32025ce43e
    # see also https://www.textrazor.com/types
    labels:
      "Place": "GEO"
      "Person": "PERSON"
      "Organisation" : "ORG"
      "Company": "ORG"
      "Disease": "KEYWORD"
      "Species": "KEYWORD"
      "AnatomicalStructure": "KEYWORD"
      "Drug": "KEYWORD"
      "ChemicalSubstance": "KEYWORD"
      "Work": "PRODUCT"
      "EthnicGroup": "KEYWORD"
      "Currency": "CURRENCY"
      "URL": "URL"
      "MeanOfTransportation": "PRODUCT"
      "Event": "EVENT"
      "Sport": "KEYWORD"
      "Holiday": "EVENT"
      "CelestialBody": "KEYWORD" # could also be GEO?
      "Language": "KEYWORD"
      "Activity": "EVENT"
      "Food": "PRODUCT"
      "TopicalConcept": "KEYWORD"
      "TimePeriod": "DATE"
      "Biomolecule": "KEYWORD"
      "Date": "DATE"
      "Flag": "KEYWORD"

