folder_input: "input"
folder_output: "output"
# categories can be one of these:
# PERSON, GEO, ORG, PRODUCT, EVENT, KEYWORD, FUNCTION, NUMBER, DATE, CURRENCY, URL, QUOTE
categories:
  - PERSON
  - GEO
  - ORG
engines:
  - simple
  - alchemy
  - basistech
  - bitext
  - linguasys
  - meaningcloud
  - netowl
  - repustate
  - retresco
  - semantria
  - temis
  - textrazor
