key: 7d834fdf730ac8adc0443863068fd16d291b818b
labels:
  "City": "GEO"
  "Facility": "GEO"
  "StateOrCounty": "GEO"
  "Country": "GEO"
  "Region": "GEO"
  "Continent": "GEO"
  "GeographicFeature": "GEO"
  "Person": "PERSON"
  "Company": "ORG"
  "Organization": "ORG"
  "PrintMedia": "ORG"
  "JobTitle": "FUNCTION"
  "Quantity": "NUMBER"
  "SportingEvent": "EVENT"
  "Drug": "KEYWORD"
  "HealthCondition": "KEYWORD"
  "FieldTerminology": "KEYWORD"
  "Sport": "KEYWORD"
  "Technology": "KEYWORD"
  "EntertainmentAward": "KEYWORD"
  "Holiday": "EVENT"
  "TelevisionStation": "ORG"
  "Crime": "KEYWORD"
# see http://www.alchemyapi.com/api/entity/types