host: "http://192.168.59.103:9020"
labels:
  "PERSON": "PERSON"
  "LOCATION": "GEO"
  "TITLE": "FUNCTION"
  "TEMPORAL:DATE": "DATE"
  "ORGANIZATION": "ORG"
  "IDENTIFIER:URL": "URL"
  "TEMPORAL:TIME": "DATE"
  "IDENTIFIER:DISTANCE": "NUMBER"
  "IDENTIFIER:MONEY": "CURRENCY"
  "RELIGION": "KEYWORD"
  "NATIONALITY": "KEYWORD"
  "PRODUCT": "PRODUCT"
