key: 18f6730269b89e61a2d9c89853960328aa5511226830cf32025ce43e
# see also https://www.textrazor.com/types
labels:
  "Place": "GEO"
  "Person": "PERSON"
  "Organisation" : "ORG"
  "Company": "ORG"
  "Disease": "KEYWORD"
  "Species": "KEYWORD"
  "AnatomicalStructure": "KEYWORD"
  "Drug": "KEYWORD"
  "ChemicalSubstance": "KEYWORD"
  "Work": "PRODUCT"
  "EthnicGroup": "KEYWORD"
  "Currency": "CURRENCY"
  "URL": "URL"
  "MeanOfTransportation": "PRODUCT"
  "Event": "EVENT"
  "Sport": "KEYWORD"
  "Holiday": "EVENT"
  "CelestialBody": "KEYWORD" # could also be GEO?
  "Language": "KEYWORD"
  "Activity": "EVENT"
  "Food": "PRODUCT"
  "TopicalConcept": "KEYWORD"
  "TimePeriod": "DATE"
  "Biomolecule": "KEYWORD"
  "Date": "DATE"
  "Flag": "KEYWORD"