key: 317542394cddce0baf6b3ec698d92198e2b6e4a7
labels:
  "government.politician": "PERSON"
  "location.citytown": "GEO"
  "location.us_state": "GEO"
  "location.country": "GEO"
  "location.region": "GEO"
  "location.continent": "GEO"
  "location.nationality": "KEYWORD"
  "business.businessmen": "PERSON"
  "government.agency": "ORG"
  "government.political_party": "ORG"
  "government.us_presidents": "PERSON"
  "government.position": "FUNCTION"
  "business.job_title": "FUNCTION"
  "business.brand": "PRODUCT"
  "business.oil_and_gas_drilling_and_exploration": "ORG"
  "business.apparel_stores": "PRODUCT"
  "time.month": "DATE"
  "time.day": "DATE"
  "time.season": "DATE"
  "news.network": "ORG"
  "health.disease": "KEYWORD"
  "health.vaccine": "KEYWORD"
  "travel.hotel": "KEYWORD"
  "travel.accommodation": "KEYWORD"
  "health.physician": "PERSON"
  "sports.sports_team_coach": "PERSON"
  "sports.pro_athlete": "PERSON"
  "finance.currency": "CURRENCY"
  "automotive.model": "PRODUCT"
  "automotive.company": "ORG"
  "music.album": "PRODUCT"
# see also here: https://www.repustate.com/media/entities.txt
