key: 1e9489fd-9870-45c3-9cd2-0890aafad3fa
secret: 02f32cbb-0e0a-4150-a93a-b36d28b99cfd
# see http://support.semantria.com/customer/portal/articles/838464-entity-extraction
labels:
  "Place": "GEO"
  "Person": "PERSON"
  "Product": "PRODUCT"
  "Company": "ORG"
  "Job Title": "FUNCTION"
  "Quote": "QUOTE"
  "Pattern": "KEYWORD"
  "vehicle": "PRODUCT"
# in semantria the configuration is stored on the server and has an id
# You can get the config id for a language via
# for key in session.getConfigurations(): print key["language"],key["config_id"]
langs:
  "ko": "bc399d26-9b33-4f00-a7fe-cb343f8a3756"
  "it": "72bad261-4240-4cf6-b3e3-5fb27bc9c619"
  "jp": "ebda1e20-d666-4533-9614-1e3d02bcb22c"
  "fr": "aa2141a3-f990-4296-a82b-daf7f2ee9d9e"
  "pt": "5aa3cc21-7c82-463a-8307-de815573e4ed"
  "en": "10781931-a7cc-4ff8-aae1-5bda0a7fcec9"
  "ms": "d9f02606-f087-45e4-9643-77d0ddd4f4cc"
  "de": "04854264-0288-420f-8954-104ab6cc5b1a"
  "es": "bd5e9a9b-3772-460c-9fd3-3915ee9c95ec"
  "zh": "2fc65284-5743-4ff4-b239-331ac9b03a7a"