user: amaier1
passwd: Qp76dY1DQ
labels:
  19: "NUMBER"
  15: "CURRENCY"
  11: "DATE"
  10: "DATE"
  8: "URL"
  7: "ORG"
  6: "ORG"
  3: "GEO"
  1: "PERSON"
  0: "KEYWORD"
langs:
  "en": "ENG"
  "de": "DEU"
  "es": "ESP"
  "pt": "POR"
  "it": "ITA"
  "fr": "FRA"
  "nl": "NLD"
  "ca": "CAT"
